### ISSUE TITLE
创建完后连不上网

### ISSUE THREAD

**Issue by predb** [FunctionClub/MTProxy-Bash#1]
你好，
同一个宽带下，同一个 VPS （AWS）下创建的 Shadowsocks 服务器是正常使用的，
但是这个创建完，在 TG 里面使用的时候，连不上网，一直是 Connecting……，
会是哪里的问题？AWS 防火墙？
或者是我端口「18611」设置有误？

**Comment by ancoo** [comment]
同样问题 老铁怎么解决的

**Comment by predb** [comment]
没解决

**Comment by ghost** [comment]
AWS请使用脚本里面的 NAT 模式，谢谢。记录你的内网ip 和 外网ip，填写进去就行
